<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [73]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [74]:
%%sql

SELECT
  orderdate,
  netprice
FROM sales
WHERE netprice > 100
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  netprice
0  2015-01-01    659.78
1  2015-01-01    286.69
2  2015-01-01    135.75
3  2015-01-01    434.30
4  2015-01-01    113.57
5  2015-01-01    499.45
6  2015-01-01   2067.75
7  2015-01-01    152.00
8  2015-01-01    310.46
9  2015-01-01    222.00

In [75]:
%sql SELECT COUNT(*) FROM sales WHERE quantity > 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   count
0  34725

In [76]:
%%time
%%sql
SELECT
  *
FROM product

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2517 rows affected.

CPU times: user 20.2 ms, sys: 1.02 ms, total: 21.2 ms
Wall time: 26.9 ms

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2513,505026,Contoso Bluetooth Active Headphones L15 Red,"Contoso, Ltd",Contoso,Red,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2513,2514,505027,Contoso Bluetooth Active Headphones L15 White,"Contoso, Ltd",Contoso,White,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2514,2515,505028,Contoso In-Line Coupler E180 White,"Contoso, Ltd",Contoso,White,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2515,2516,505029,Contoso In-Line Coupler E180 Black,"Contoso, Ltd",Contoso,Black,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2516,2517,505030,Contoso In-Line Coupler E180 Silver,"Contoso, Ltd",Contoso,Silver,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories

In [77]:
%%sql
SELECT
  state,
  COUNT(*)
FROM customer
GROUP BY
  state

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

565 rows affected.

         state  count
0           KS    511
1           EN      8
2        Conwy     64
3      Norfolk    271
4           FG     19
..         ...    ...
560         GD     79
561      Fylde     42
562  Allerdale     35
563         NT    145
564         AV     56

[565 rows x 2 columns]

In [78]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [79]:
%%sql
SELECT
  DISTINCT(fromcurrency) AS currency
From currencyexchange
UNION
SELECT
  DISTINCT(tocurrency)
FROM currencyexchange

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

  currency
0      CAD
1      EUR
2      AUD
3      USD
4      GBP

In [80]:
%%sql
SELECT * FROM product LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [81]:
%%sql

SELECT
  p.categoryname,
  MAX(p.price) AS mostexpensive,
  (SELECT p2.productname FROM product p2 WHERE p2.categoryname = p.categoryname ORDER BY p2.price DESC LIMIT 1) AS productname
FROM product AS p
GROUP BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,mostexpensive,productname
0,Audio,299.23,Contoso 8GB Clock & Radio MP3 Player X850 Silver
1,Cell phones,589.00,The Phone Company Touch Screen Phone 1600 TFT-...
2,Cameras and camcorders,1620.00,"Fabrikam Independent Filmmaker 1"" 25mm X400 Blue"
3,TV and Video,2899.99,"Adventure Works 52"" LCD HDTV X590 Silver"
4,Home Appliances,3199.99,Fabrikam Refrigerator 24.7CuFt X9800 White
5,Games and Toys,598.80,MGS Age of Empires Expansion: The Rise of Rome...
6,"Music, Movies and Audio Books",289.99,SV DVD 15-Inch Player Portable L200 Black
7,Computers,2499.00,Proseware Projector 1080p DLP86 Black

In [82]:
%%sql
SELECT * FROM sales LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64

In [83]:
%%sql
SELECT * FROM customer LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17

In [84]:
%sql SELECT * FROM store LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None

In [85]:
%%sql
SELECT
  COUNT(DISTINCT s.orderkey) AS NumberOfOrders,
  c.countryfull
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
GROUP BY c.countryfull
ORDER BY NumberOfOrders DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

   numberoforders     countryfull
0           43531   United States
1            8888         Germany
2            8717          Canada
3            8578  United Kingdom
4            4937       Australia
5            3483     Netherlands
6            2597          France
7            2399           Italy

In [86]:
%%sql
SELECT st.countryname, COUNT(DISTINCT s.orderkey) orders
FROM sales s
JOIN store st
USING(storekey)
GROUP BY countryname
ORDER BY orders DESC;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

9 rows affected.

      countryname  orders
0          Online   32482
1   United States   26488
2  United Kingdom    5674
3          Canada    5230
4         Germany    5224
5       Australia    2862
6     Netherlands    2066
7           Italy    1640
8          France    1464

In [87]:
%%sql

WITH OrdersByStoreCountry AS (
  SELECT
    st.countryname,
    COUNT(DISTINCT s.orderkey) AS orders
  FROM sales s
  JOIN store st
  USING(storekey)
  GROUP BY st.countryname
)
SELECT
  SUM(orders) AS TotalOrders
FROM OrdersByStoreCountry;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  totalorders
0       83130

In [88]:
%%sql
WITH OrdersByStoreCountry AS (
SELECT
  COUNT(DISTINCT s.orderkey) AS NumberOfOrders,
  c.countryfull
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
GROUP BY c.countryfull
ORDER BY NumberOfOrders DESC)
SELECT
  SUM(NumberOfOrders)
FROM OrdersByStoreCountry

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

     sum
0  83130

In [89]:
%%sql
SELECT
  s.orderdate,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN c.customerkey END) AS eu_customer,
  COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN c.customerkey END) AS au_customer,
  COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN c.customerkey END) AS usa_customer,
  COUNT(DISTINCT s.customerkey) AS total_customer
FROM
  sales s
LEFT JOIN customer c ON  s.customerkey = c.customerkey
WHERE
  s.orderdate BETWEEN '01-01-2023' AND '12-31-2023'
GROUP BY
  s.orderdate
ORDER BY
  s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  eu_customer  au_customer  usa_customer  total_customer
0    2023-01-01            6            1             5              12
1    2023-01-02           15            3            31              49
2    2023-01-03           17            3            44              64
3    2023-01-04           28            4            46              78
4    2023-01-05           22            8            57              87
..          ...          ...          ...           ...             ...
359  2023-12-27           26            6            41              73
360  2023-12-28           24            7            44              75
361  2023-12-29           19            4            32              55
362  2023-12-30           25           16            50              91
363  2023-12-31            1            0             8               9

[364 rows x 5 columns]

In [90]:
%%sql
SELECT
  continent
FROM
  customer
GROUP BY
  continent

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0         Europe
1  North America
2      Australia

In [91]:
%%sql
SELECT * FROM sales LIMIT 1;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64

In [92]:
%%sql
SELECT * FROM product LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3

In [93]:
%%sql
SELECT
  p.categoryname AS category,
  SUM(CASE WHEN s.orderdate BETWEEN '01-01-2022' AND '12-31-2022' THEN (s.quantity*s.netprice*s.exchangerate) ELSE 0 END) AS total_revenue_2022,
  SUM(CASE WHEN s.orderdate BETWEEN '01-01-2023' AND '12-31-2023' THEN (s.quantity*s.netprice*s.exchangerate) ELSE 0 END) AS total_revenue_2023
FROM
  sales s
LEFT JOIN
  product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  total_revenue_2022  total_revenue_2023
0                          Audio           766938.21           688690.18
1        Cameras and camcorders           2382532.56          1983546.29
2                    Cell phones          8119665.07          6002147.63
3                      Computers         17862213.49         11650867.21
4                 Games and Toys           316127.30           270374.96
5                Home Appliances          6612446.68          5919992.87
6  Music, Movies and Audio Books          2989297.28          2180768.13
7                   TV and Video          5815336.61          4412178.23

In [94]:
%%sql
SELECT * FROM sales LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64

In [95]:
%%sql
SELECT * FROM customer LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17

In [96]:
%%sql
SELECT * FROM store LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None

In [97]:
%%sql
SELECT * FROM product LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3

In [98]:
%%sql
SELECT
  st.storekey,
  st.description,
  COUNT(DISTINCT CASE WHEN c.gender = 'male' THEN s.orderkey END) AS male,
  COUNT(DISTINCT CASE WHEN c.gender = 'female' THEN s.orderkey END) AS female,
  COUNT(DISTINCT s.orderkey) AS total
FROM
  sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN store st ON s.storekey = st.storekey
WHERE
  s.orderdate BETWEEN '01-01-2023' AND '12-31-2023'
GROUP BY
  st.storekey
ORDER BY
  st.storekey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

58 rows affected.

    storekey                                 description  male  female  total
0         10  Contoso Store Australian Capital Territory    27      28     55
1         35               Contoso Store South Australia    47      46     93
2         40                      Contoso Store Tasmania    39      31     70
3         50                      Contoso Store Victoria    65      59    124
4         60             Contoso Store Western Australia    37      48     85
5         74                 Contoso Store New Brunswick   103      92    195
6         80     Contoso Store Newfoundland and Labrador    94      85    179
7         90         Contoso Store Northwest Territories    65      87    152
8        100                       Contoso Store Nunavut    75      86    161
9        120               Contoso Store Basse-Normandie    14      25     39
10       130                         Contoso Store Corse    11      16     27
11       140                 Contoso Store Franche-Comté    23      21     44
12       150                    Contoso Store La Réunion    12      13     25
13       160                      Contoso Store Limousin    16      13     29
14       170                    Contoso Store Martinique    18       8     26
15       180                       Contoso Store Mayotte    18      19     37
16       190                        Contoso Store Berlin    44      50     94
17       210       Contoso Store Freie Hansestadt Bremen    48      41     89
18       220           Contoso Store Freistaat Thüringen    48      74    122
19       230                       Contoso Store Hamburg    46      51     97
20       240                        Contoso Store Hessen    45      56    101
21       255        Contoso Store Mecklenburg-Vorpommern    41      44     85
22       260                      Contoso Store Saarland    47      45     92
23       270                Contoso Store Sachsen-Anhalt    39      50     89
24       290                          Contoso Store Enna    36      29     65
25       300                        Contoso Store Pesaro    41      28     69
26       310                       Contoso Store Drenthe    50      37     87
27       320                     Contoso Store Flevoland    48      38     86
28       330                     Contoso Store Friesland    48      38     86
29       340                     Contoso Store Groningen    50      45     95
30       360                        Contoso Store Armagh    33      36     69
31       370                      Contoso Store Ayrshire    45      26     71
32       380                       Contoso Store Belfast    39      61    100
33       390                 Contoso Store Blaenau Gwent    47      31     78
34       400    Contoso Store Dungannon and South Tyrone    60      42    102
35       420                    Contoso Store North Down    36      50     86
36       430                        Contoso Store Alaska    59      73    132
37       440                      Contoso Store Arkansas    76      78    154
38       450                   Contoso Store Connecticut    75      85    160
39       470                        Contoso Store Hawaii    46      54    100
40       480                         Contoso Store Idaho    74      79    153
41       490                          Contoso Store Iowa    70      81    151
42       500                        Contoso Store Kansas    84      84    168
43       510                         Contoso Store Maine    74      81    155
44       530                       Contoso Store Montana    64      70    134
45       540                      Contoso Store Nebraska    86      62    148
46       550                        Contoso Store Nevada    82      70    152
47       560                 Contoso Store New Hampshire    74      58    132
48       570                    Contoso Store New Mexico    65      59    124
49       585                  Contoso Store North Dakota    72      42    114
50       590                        Contoso Store Oregon    83      75    158
51       605                  Contoso Store Rhode Island    70      70    140
52       610                Contoso Store South Carolina    73      73    146
53       620                  Contoso Store South Dakota    74      67    141
54       650                 Contoso Store Washington DC    89      54    143
55       660                 Contoso Store West Virginia    67      50    117
56       670                       Contoso Store Wyoming    70      72    142
57    999999                                Online store  4628    4807   9435

In [99]:
%%sql
SELECT
  p.color,
  SUM(CASE WHEN (c.age BETWEEN 18 AND 25) THEN (s.netprice * s.quantity * s.exchangerate) ELSE 0 END) AS age_18_25,
  SUM(CASE WHEN (c.age BETWEEN 26 AND 35) THEN (s.netprice * s.quantity * s.exchangerate) ELSE 0 END) AS age_26_35,
  SUM(CASE WHEN (c.age BETWEEN 36 AND 45) THEN (s.netprice * s.quantity * s.exchangerate) ELSE 0 END) AS age_36_45,
  SUM(CASE WHEN (c.age > 45) THEN (s.netprice * s.quantity * s.exchangerate) ELSE 0 END) AS age_more_than_45
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE s.orderdate BETWEEN '01-01-2023' AND '12-31-2023'
GROUP BY
  p.color

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

17 rows affected.

          color  age_18_25  age_26_35  age_36_45  age_more_than_45
0         Azure    3090.69    1774.84    4038.86          18983.02
1         Black  943552.37 1238734.41 1341317.75        5358620.36
2          blue    1787.89     120.78     120.49           2332.40
3          Blue  106355.33  218804.28  288108.29        1052231.18
4         Brown  173724.20  328400.92  263582.64        1236801.78
5          Gold  103767.39  160052.97  208220.43         741488.38
6         Green   76812.16  210850.64   98165.38         464677.93
7          Grey  248999.05  340149.05  369611.65        1459721.76
8        Orange   26824.11   26681.98   22936.18         234684.26
9          Pink   59398.18  100738.15  114540.22         386449.24
10       Purple    1751.31    2199.15    3233.73           9360.40
11          Red  127271.43  160539.77  172419.66         668434.00
12       Silver  679973.36  948716.53  952253.88        3791172.41
13  Silver Grey   16531.91   17201.12   10310.53          89072.43
14  Transparent      83.02      59.49      52.96            215.82
15        White  793944.27 1044751.65 1117895.75        4320252.64
16       Yellow   14507.48   15160.79   16556.43          97391.98

In [100]:
%sql SELECT * FROM sales LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64

In [101]:
%sql SELECT * FROM product LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3

In [102]:
%%sql
SELECT
  p.subcategoryname,
  COUNT(DISTINCT CASE WHEN p.price < 1000 THEN s.orderkey END) AS less_1k,
  COUNT(DISTINCT CASE WHEN p.price BETWEEN 1000 AND 2000 THEN s.orderkey END) AS bt1K_2k,
  COUNT(DISTINCT CASE WHEN p.price > 2000 THEN s.orderkey END) AS over2k
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE s.orderdate BETWEEN '01-01-2023' AND '12-31-2023'
GROUP BY p.subcategoryname
ORDER BY p.subcategoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

32 rows affected.

                     subcategoryname  less_1k  bt1k_2k  over2k
0                   Air Conditioners      352        0       0
1               Bluetooth Headphones      825        0       0
2                        Boxed Games     1917        0       0
3                         Camcorders      249       77       0
4   Cameras & Camcorders Accessories      358        0       0
5                          Car Video      543        0       0
6            Cell phones Accessories     1518        0       0
7                    Coffee Machines      280       41       0
8              Computers Accessories     1210        0       0
9                           Desktops     2421        0       0
10                   Digital Cameras      345        0       0
11               Digital SLR Cameras      591        0       0
12                    Download Games     1251        0       0
13                              Fans      228        0       0
14              Home & Office Phones     1376        0       0
15               Home Theater System      341        4       0
16                             Lamps      229        0       0
17                           Laptops     1027      199       0
18                        Microwaves      567        0       0
19                          Monitors     1243        0       0
20                         Movie DVD     5359        0       0
21                           MP4&MP3      342        0       0
22          Printers, Scanners & Fax     1199        0       0
23              Projectors & Screens     1050        0     235
24                     Recording Pen      429        0       0
25                     Refrigerators      300        0      51
26              Smart phones & PDAs      3258        0       0
27                       Televisions      778      315     105
28              Touch Screen Phones      2712        0       0
29                         VCD & DVD      489        0       0
30                  Washers & Dryers       50      136      58
31                     Water Heaters      630      172       0

In [103]:
%%sql
SELECT
    st.countryname,
    SUM(CASE WHEN st.squaremeters < 1000 THEN (s.netprice*s.quantity*s.exchangerate) ELSE 0 END) AS small,
    SUM(CASE WHEN st.squaremeters BETWEEN 1000 AND 2000 THEN (s.netprice*s.quantity*s.exchangerate) ELSE 0 END) AS medium,
    SUM(CASE WHEN st.squaremeters > 2000 THEN (s.netprice*s.quantity*s.exchangerate) ELSE 0 END) AS large
FROM sales s
LEFT JOIN store st ON s.storekey = st.storekey
WHERE
  s.orderdate BETWEEN '01-01-2023' AND '12-31-2023'
  AND st.countryname != 'Online'
GROUP BY st.countryname
ORDER BY st.countryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

      countryname     small     medium      large
0       Australia 152603.07  805753.93  332051.57
1          Canada      0.00  810136.00 1098302.94
2          France 387769.84       0.00       0.00
3         Germany 329324.58 1025798.82  192337.50
4           Italy      0.00  205734.46  142339.35
5     Netherlands 157601.88  448792.47       0.00
6  United Kingdom      0.00  642214.71  229729.64
7   United States 282562.90 5528952.03  246768.97

In [104]:
%%sql
SELECT * FROM customer LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17

In [105]:
%%sql
SELECT * FROM sales LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64

In [106]:
%%sql
SELECT
  c.continent,
  AVG(CASE WHEN s.orderdate BETWEEN '01-01-2022' AND '12-31-2022' THEN (s.netprice*s.quantity*s.exchangerate) ELSE 0 END) AS avg_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '01-01-2022' AND '12-31-2022' THEN (s.netprice*s.quantity*s.exchangerate) ELSE 0 END) AS max_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '01-01-2022' AND '12-31-2022' THEN (s.netprice*s.quantity*s.exchangerate) ELSE 0 END) AS min_2022
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
GROUP BY c.continent
ORDER BY avg_2022 DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent  avg_2022  max_2022  min_2022
0      Australia    330.26  24182.95      0.00
1  North America    235.06  38082.66      0.00
2         Europe    182.91  25725.87      0.00

In [107]:
%%sql
SELECT
    c.continent,
    AVG(s.quantity * s.netprice * s.exchangerate) AS avg_net_revenue_2022,
    MIN(s.quantity * s.netprice * s.exchangerate) AS min_net_revenue_2022,
    MAX(s.quantity * s.netprice * s.exchangerate) AS max_net_revenue_2022
FROM
    sales s
    LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE
    s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY
    c.continent;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

,continent,avg_net_revenue_2022,min_net_revenue_2022,max_net_revenue_2022
0,Australia,1336.18,4.54,24182.95
1,Europe,860.21,1.68,25725.87
2,North America,999.22,0.83,38082.66

In [108]:
%%sql
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE column_name = 'countryname'
  AND table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  table_name  column_name          data_type
0      store  countryname  character varying

In [109]:
%%sql
SELECT
    p.categoryname,
    AVG(CASE WHEN st.squaremeters < 1000 THEN (s.netprice*s.quantity*s.exchangerate) END) AS small,
    AVG(CASE WHEN st.squaremeters BETWEEN 1000 AND 2000 THEN (s.netprice*s.quantity*s.exchangerate) END) AS medium,
    AVG(CASE WHEN st.squaremeters > 2000 THEN (s.netprice*s.quantity*s.exchangerate)  END) AS large
FROM sales s
LEFT JOIN store st ON s.storekey = st.storekey
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname   small  medium   large
0                          Audio  329.00  336.86  347.52
1        Cameras and camcorders  1392.44 1391.82 1600.37
2                    Cell phones  778.91  821.71  853.67
3                      Computers 1974.16 2119.08 2259.95
4                 Games and Toys   83.72   82.48   84.00
5                Home Appliances 1390.73 1522.02 1522.81
6  Music, Movies and Audio Books  301.18  318.26  332.62
7                   TV and Video 1479.13 1412.76 1532.97

In [110]:
%%sql
SELECT
  c.countryfull,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-03-31' THEN (s.netprice*s.quantity*s.exchangerate) END) AS Q1,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-04-01' AND '2023-06-30' THEN (s.netprice*s.quantity*s.exchangerate) END) AS Q2,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-07-01' AND '2023-09-30' THEN (s.netprice*s.quantity*s.exchangerate) END) AS Q3,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-10-01' AND '2023-12-31' THEN (s.netprice*s.quantity*s.exchangerate) END) AS Q4
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
GROUP BY c.countryfull

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

      countryfull       q1       q2       q3       q4
0       Australia 15402.31 16019.39 16719.22 29075.44
1          Canada 25424.67 28264.64 27611.60 32915.59
2          France 15375.42 14358.10 13546.29  9365.31
3         Germany 25772.22 19249.54 17350.34 14751.06
4           Italy 13170.85 11000.96 12268.68  7821.64
5     Netherlands 18137.03 15350.72 11888.10 17540.68
6  United Kingdom 15582.22 18072.26 19456.28 17403.32
7   United States 23868.00 26679.91 25087.92 20655.00

In [111]:
%%sql
SELECT
 countryfull
FROM customer
group by countryfull

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

      countryfull
0  United Kingdom
1     Netherlands
2           Italy
3       Australia
4         Germany
5          Canada
6   United States
7          France

In [112]:
%%sql
SELECT
  st.countryname,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY(CASE WHEN c.age < 30 THEN (s.netprice*s.quantity*s.exchangerate) END)) AS young,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY(CASE WHEN c.age BETWEEN 30 AND 50 THEN (s.netprice*s.quantity*s.exchangerate) END)) AS middle_age,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY(CASE WHEN c.age > 50 THEN (s.netprice*s.quantity*s.exchangerate) END)) AS senior
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN store st ON s.storekey = st.storekey
GROUP BY st.countryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

9 rows affected.

      countryname  young  middle_age  senior
0       Australia 589.32      556.49  608.88
1          Canada 515.31      560.68  530.06
2          France 332.01      367.02  377.58
3         Germany 342.64      363.95  344.88
4           Italy 395.01      343.75  343.18
5     Netherlands 344.43      392.51  344.05
6          Online 399.99      392.38  399.84
7  United Kingdom 309.04      296.78  317.01
8   United States 404.62      404.97  400.49

In [113]:
%%sql
SELECT
  p.categoryname,
  SUM(CASE WHEN c.age < 25 THEN (s.netprice*s.quantity*s.exchangerate) END) AS young,
  SUM(CASE WHEN c.age BETWEEN 25 AND 44 THEN (s.netprice*s.quantity*s.exchangerate) END) AS middle_age,
  SUM(CASE WHEN c.age > 45 THEN (s.netprice*s.quantity*s.exchangerate) END) AS old
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname      young  middle_age         old
0                          Audio  484344.28  1548765.21  3201115.82
1        Cameras and camcorders  1584675.41  5605447.41 11053850.79
2                    Cell phones 2921769.45  9790779.71 19441667.54
3                      Computers 8401282.31 27776587.47 53255130.72
4                 Games and Toys  149626.73   476605.00  1016634.74
5                Home Appliances 2374573.85  7926333.73 15939383.31
6  Music, Movies and Audio Books  956110.81  3206680.30  6292430.07
7                   TV and Video 1996254.92  6184153.64 12032481.04

In [114]:
%%sql
SELECT
    p.categoryname,
    CASE
        WHEN c.age < 25 THEN '<25'
        WHEN c.age BETWEEN 25 AND 44 THEN '25-44'
        ELSE '45+'
    END AS age_group,
    SUM(s.quantity * s.netprice * s.exchangerate) AS total_purchases
FROM sales s
INNER JOIN customer c ON s.customerkey = c.customerkey
INNER JOIN product p ON s.productkey = p.productkey
GROUP BY
    age_group,
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                     categoryname age_group  total_purchases
0                           Audio       <25        484344.28
1         Cameras and camcorders        <25       1584675.41
2                     Cell phones       <25       2921769.45
3                       Computers       <25       8401282.31
4                  Games and Toys       <25        149626.73
5                 Home Appliances       <25       2374573.85
6   Music, Movies and Audio Books       <25        956110.81
7                    TV and Video       <25       1996254.92
8                           Audio     25-44       1548765.21
9         Cameras and camcorders      25-44       5605447.41
10                    Cell phones     25-44       9790779.71
11                      Computers     25-44      27776587.47
12                 Games and Toys     25-44        476605.00
13                Home Appliances     25-44       7926333.73
14  Music, Movies and Audio Books     25-44       3206680.30
15                   TV and Video     25-44       6184153.64
16                          Audio       45+       3279788.61
17        Cameras and camcorders        45+      11330237.85
18                    Cell phones       45+      19911716.55
19                      Computers       45+      54441152.27
20                 Games and Toys       45+       1042342.41
21                Home Appliances       45+      16306337.96
22  Music, Movies and Audio Books       45+       6425519.88
23                   TV and Video       45+      12286452.82

In [115]:
%%sql
SELECT
    s.customerkey,
    CASE
        WHEN SUM(s.quantity * s.netprice * s.exchangerate) < 500 THEN 'Low Spender'
        WHEN SUM(s.quantity * s.netprice * s.exchangerate) BETWEEN 500 AND 2000 THEN 'Medium Spender'
        ELSE 'High Spender'
    END AS spender,
    SUM(s.quantity * s.netprice * s.exchangerate) AS total_purchases
FROM sales s
WHERE s.orderdate BETWEEN '01-01-2023' AND '12-31-2023'
GROUP BY
    s.customerkey
ORDER BY
    s.customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

13746 rows affected.

       customerkey         spender  total_purchases
0              180  Medium Spender          1984.90
1              387  Medium Spender          1019.74
2              545    High Spender          3551.47
3              649  Medium Spender          1749.11
4              688    High Spender         16909.04
...            ...             ...              ...
13741      2099174     Low Spender           299.00
13742      2099336     Low Spender           358.88
13743      2099511    High Spender          2856.02
13744      2099656    High Spender          8328.22
13745      2099743  Medium Spender           598.46

[13746 rows x 3 columns]

In [117]:
%sql SELECT * FROM product LIMIT 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3

In [158]:
%%sql
SELECT
    CASE
      WHEN weight IS NULL OR weightunit IS NULL THEN '1 - No Weight Specified'
      WHEN weightunit = 'pounds' AND weight < 5 THEN '2 - Very Light (< 5 lbs)'
      WHEN weightunit = 'pounds' AND weight BETWEEN 5 AND 25 THEN '3 - Light (5-25 lbs)'
      WHEN weightunit = 'pounds' AND weight BETWEEN 25 AND 100 THEN '4 - Medium (25-100 lbs)'
      WHEN weightunit = 'pounds' AND weight > 100 THEN '5 - Heavy (> 100 lbs)'
      WHEN weightunit = 'ounces' AND weight < 5 THEN '6 - Light Ounces (< 5 oz)'
      WHEN weightunit = 'ounces' AND weight >= 5 THEN '7 - Heavy Ounces (≥ 5 oz)'
      WHEN weightunit = 'grams' THEN '8 - Metric Weights'
      ELSE '9 - Other Weight Categories'
    END AS weight_category,
    COUNT(productkey) AS count_category
FROM
    product
GROUP BY
    weight_category
ORDER BY
    weight_category

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

             weight_category  count_category
0    1 - No Weight Specified             284
1   2 - Very Light (< 5 lbs)             568
2       3 - Light (5-25 lbs)             751
3    4 - Medium (25-100 lbs)             391
4      5 - Heavy (> 100 lbs)             112
5  6 - Light Ounces (< 5 oz)             225
6  7 - Heavy Ounces (≥ 5 oz)             176
7         8 - Metric Weights              10